---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _plattforms
  label: Plattforms
  create: all
  match: "**/*"
  templates:
  - cases
- type: directory
  path: _data
  label: data
  create: all
  match: "*"
- type: document
  path: _data/press.yml
  label: press
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _cases
  label: Cases
  create: all
  match: "**/*"
- type: directory
  path: _work
  label: Work
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: https://res.cloudinary.com/media4e7/image/upload
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
